/*
 * Copyright (c) 2025 michioxd
 * Released under MIT license. See LICENSE for more details.
 * Repository: https://github.com/michioxd/nyaadenwa
 */

import { accentColorPropDef } from "@radix-ui/themes/src/props/color.prop.js";
import { IconType } from "react-icons/lib";
import {
    PiAndroidLogoDuotone,
    PiBookDuotone,
    PiFileArchiveDuotone,
    PiFileAudioDuotone,
    PiFileCodeDuotone,
    PiFileDocDuotone,
    PiFileDuotone,
    PiFileImageDuotone,
    PiFilePdfDuotone,
    PiFilePptDuotone,
    PiFileSqlDuotone,
    PiFileTextDuotone,
    PiFileVideoDuotone,
    PiFileXlsDuotone,
    PiFolderDuotone,
    PiGearDuotone,
} from "react-icons/pi";

export const fileExtension = {
    android_package: ["apk"],
    archive: [
        "zip",
        "7z",
        "rar",
        "tar",
        "gz",
        "bz2",
        "xz",
        "deb",
        "rpm",
        "msi",
        "dmg",
        "pkg",
        "cab",
        "iso",
        "jar",
        "arj",
        "lzh",
        "ace",
        "z",
        "sit",
        "sea",
        "cbr",
        "cbz",
    ],
    image: [
        "jpg",
        "jpeg",
        "png",
        "gif",
        "bmp",
        "webp",
        "svg",
        "ico",
        "heic",
        "heif",
        "hevc",
        "tiff",
        "tif",
        "raw",
        "cr2",
        "nef",
        "orf",
        "sr2",
        "psd",
        "ai",
        "eps",
    ],
    video: [
        "mp4",
        "avi",
        "mkv",
        "mov",
        "wmv",
        "flv",
        "webm",
        "m4v",
        "3gp",
        "3g2",
        "mj2",
        "m2ts",
        "mts",
        "m2t",
        "vob",
        "ogv",
        "rm",
        "rmvb",
        "asf",
        "mpg",
        "mpeg",
    ],
    audio: ["mp3", "wav", "aac", "flac", "ogg", "wma", "m4a", "amr", "aiff", "alac", "opus", "mid", "midi", "ra", "au"],
    document: ["doc", "docx", "odt", "rtf", "tex"],
    spreadsheet: ["xls", "xlsx", "ods", "csv", "tsv"],
    presentation: ["ppt", "pptx", "odp", "key"],
    pdf: ["pdf"],
    font: ["ttf", "otf", "woff", "woff2", "eot", "fon"],
    executable: ["exe", "bat", "cmd", "sh", "bin", "run", "app", "msi", "apk", "com", "gadget", "wsf"],
    code: [
        "js",
        "jsx",
        "ts",
        "tsx",
        "py",
        "java",
        "c",
        "cpp",
        "h",
        "cs",
        "rb",
        "php",
        "go",
        "rs",
        "swift",
        "kt",
        "kts",
        "scala",
        "pl",
        "sh",
        "bat",
        "ps1",
        "lua",
        "r",
        "m",
        "vb",
        "dart",
        "sql",
        "html",
        "htm",
        "css",
        "scss",
        "less",
        "xml",
        "json",
        "yml",
        "yaml",
        "toml",
        "conf",
        "asm",
        "s",
        "v",
        "sv",
        "vhd",
        "vhdl",
        "fs",
        "fsx",
        "fsi",
        "fsscript",
        "jl",
        "groovy",
        "clj",
        "cljs",
        "cljc",
        "edn",
        "coffee",
        "tsv",
        "ipynb",
        "abap",
        "aes",
        "apex",
        "cls",
        "trigger",
        "azcli",
        "bicep",
        "cameligo",
        "mligo",
        "clojure",
        "coffeescript",
        "csp",
        "dockerfile",
        "Dockerfile",
        "ecl",
        "elixir",
        "ex",
        "exs",
        "flow9",
        "flow",
        "freemarker2",
        "ftl",
        "graphql",
        "gql",
        "handlebars",
        "hbs",
        "hcl",
        "tf",
        "tfvars",
        "razor",
        "javascript",
        "cjs",
        "mjs",
        "julia",
        "lexon",
        "liquid",
        "m3",
        "markdown",
        "mips",
        "msdax",
        "dax",
        "mysql",
        "objective-c",
        "mm",
        "pascal",
        "pas",
        "pascaligo",
        "pgsql",
        "postgresql",
        "php3",
        "php4",
        "php5",
        "php7",
        "phps",
        "phpt",
        "pla",
        "postiats",
        "dats",
        "powerquery",
        "pq",
        "protobuf",
        "proto",
        "pug",
        "jade",
        "qsharp",
        "qs",
        "redis",
        "redshift",
        "restructuredtext",
        "rst",
        "sb",
        "scheme",
        "scm",
        "ss",
        "sol",
        "sparql",
        "st",
        "systemverilog",
        "svh",
        "tcl",
        "twig",
        "zig",
    ],
    text: ["txt", "md", "rst", "log", "ini", "conf", "cfg", "nfo", "me", "readme", "changelog", "license"],
    subtitle: ["srt", "sub", "ass", "ssa", "vtt", "sbv", "mpl"],
    database: [
        "db",
        "sql",
        "sqlite",
        "sqlite3",
        "dbf",
        "mdb",
        "accdb",
        "frm",
        "myd",
        "myi",
        "ndf",
        "ldf",
        "sdf",
        "db3",
    ],
    ebook: ["epub", "mobi", "azw", "azw3", "fb2", "lit", "prc", "ibooks"],
    compressed: ["gz", "bz2", "xz", "lz", "lzma", "z", "tar", "tgz", "tbz2", "txz"],
    system: ["sys", "dll", "drv", "cpl", "ocx", "vxd", "efi"],
};

export const fileExtensionIcon: {
    [key in keyof typeof fileExtension | "file" | "folder"]: {
        icon: IconType;
        color: (typeof accentColorPropDef)["color"]["values"][number];
    };
} = {
    android_package: {
        icon: PiAndroidLogoDuotone,
        color: "green",
    },
    archive: {
        icon: PiFileArchiveDuotone,
        color: "gray",
    },
    image: {
        icon: PiFileImageDuotone,
        color: "grass",
    },
    video: {
        icon: PiFileVideoDuotone,
        color: "indigo",
    },
    audio: {
        icon: PiFileAudioDuotone,
        color: "red",
    },
    document: {
        icon: PiFileDocDuotone,
        color: "blue",
    },
    spreadsheet: {
        icon: PiFileXlsDuotone,
        color: "green",
    },
    presentation: {
        icon: PiFilePptDuotone,
        color: "ruby",
    },
    pdf: {
        icon: PiFilePdfDuotone,
        color: "tomato",
    },
    code: {
        icon: PiFileCodeDuotone,
        color: "gray",
    },
    text: {
        icon: PiFileTextDuotone,
        color: "gray",
    },
    subtitle: {
        icon: PiFileTextDuotone,
        color: "gray",
    },
    database: {
        icon: PiFileSqlDuotone,
        color: "gray",
    },
    ebook: {
        icon: PiBookDuotone,
        color: "brown",
    },
    compressed: {
        icon: PiFileArchiveDuotone,
        color: "gray",
    },
    system: {
        icon: PiGearDuotone,
        color: "gray",
    },
    executable: {
        icon: PiGearDuotone,
        color: "gray",
    },
    font: {
        icon: PiFileDuotone,
        color: "gray",
    },
    file: {
        icon: PiFileDuotone,
        color: "gray",
    },
    folder: {
        icon: PiFolderDuotone,
        color: "yellow",
    },
};

export const editorFileLanguage = {
    abap: ["abap"],
    aes: ["aes"],
    apex: ["apex", "cls", "trigger"],
    azcli: ["azcli"],
    bash: ["sh", "bash"],
    bat: ["bat", "cmd"],
    bicep: ["bicep"],
    c: ["c", "h"],
    cameligo: ["mligo"],
    clojure: ["clj", "cljs", "cljc"],
    coffeescript: ["coffee"],
    cpp: ["cpp", "hpp"],
    csharp: ["cs"],
    csp: ["csp"],
    css: ["css", "scss", "less"],
    dockerfile: ["dockerfile", "Dockerfile"],
    ecl: ["ecl"],
    edn: ["edn"],
    elixir: ["ex", "exs"],
    flow9: ["flow"],
    freemarker2: ["ftl"],
    freemarker2_tag_angle: ["ftl"],
    freemarker2_tag_auto_bracket: ["ftl"],
    freemarker2_tag_auto_dollar: ["ftl"],
    freemarker2_tag_bracket: ["ftl"],
    freemarker2_tag_dollar: ["ftl"],
    fs: ["fs"],
    fsharp: ["fs", "fsi", "fsx", "fsscript"],
    fsi: ["fsi"],
    fsscript: ["fsscript"],
    fsx: ["fsx"],
    go: ["go"],
    graphql: ["graphql", "gql"],
    groovy: ["groovy"],
    handlebars: ["handlebars", "hbs"],
    hcl: ["hcl", "tf", "tfvars"],
    html: ["html", "htm", "razor", "handlebars"],
    ini: ["ini", "cfg", "conf"],
    java: ["java"],
    javascript: ["js", "jsx", "cjs", "mjs"],
    json: ["json"],
    julia: ["jl"],
    kotlin: ["kt", "kts"],
    less: ["less"],
    lexon: ["lexon"],
    liquid: ["liquid"],
    lua: ["lua"],
    m3: ["m3"],
    markdown: ["md", "markdown"],
    mips: ["mips"],
    msdax: ["dax", "msdax"],
    mysql: ["mysql"],
    objective: ["objective-c", "mm"],
    pascal: ["pas", "pascal"],
    pascaligo: ["pascaligo"],
    perl: ["pl"],
    pgsql: ["pgsql", "postgresql"],
    php: ["php", "php3", "php4", "php5", "php7", "phps", "phpt"],
    pla: ["pla"],
    postiats: ["dats"],
    powerquery: ["pq", "m"],
    powershell: ["ps1"],
    protobuf: ["proto"],
    pug: ["pug", "jade"],
    python: ["py"],
    qsharp: ["qs"],
    r: ["r"],
    razor: ["cshtml", "razor"],
    redis: ["redis"],
    redshift: ["redshift"],
    restructuredtext: ["rst"],
    ruby: ["rb"],
    rust: ["rs"],
    sb: ["sb"],
    scala: ["scala"],
    scheme: ["scm", "ss"],
    scss: ["scss"],
    sol: ["sol"],
    sparql: ["sparql"],
    sql: ["sql", "sqlite", "sqlite3", "db", "db3", "mdb", "accdb", "frm", "myd", "myi", "ndf", "ldf", "sdf"],
    st: ["st"],
    sv: ["sv"],
    swift: ["swift"],
    systemverilog: ["sv", "svh"],
    tcl: ["tcl"],
    twig: ["twig"],
    typescript: ["ts", "tsx"],
    v: ["v"],
    vb: ["vb"],
    vhd: ["vhd"],
    vhdl: ["vhdl"],
    xml: ["xml", "xsd", "xsl", "xslt"],
    yaml: ["yaml", "yml"],
    zig: ["zig"],
};

const mimeType = {
    "application/zip": ["zip"],
    "application/x-7z-compressed": ["7z"],
    "application/x-rar-compressed": ["rar"],
    "application/x-tar": ["tar"],
    "application/gzip": ["gz"],
    "application/x-bzip2": ["bz2"],
    "application/x-xz": ["xz"],
    "application/vnd.debian.binary-package": ["deb"],
    "application/x-rpm": ["rpm"],
    "application/x-msdownload": ["msi"],
    "application/x-apple-diskimage": ["dmg"],
    "application/vnd.apple.installer+xml": ["pkg"],
    "application/vnd.ms-cab-compressed": ["cab"],
    "application/x-iso9660-image": ["iso"],
    "application/java-archive": ["jar"],
    "application/x-arj": ["arj"],
    "application/x-lzh-compressed": ["lzh"],
    "application/x-ace-compressed": ["ace"],
    "application/x-compress": ["z"],
    "application/x-stuffit": ["sit"],
    "application/x-sea": ["sea"],
    "application/x-cbr": ["cbr", "cbz"],
    "image/jpeg": ["jpg", "jpeg"],
    "image/png": ["png"],
    "image/gif": ["gif"],
    "image/bmp": ["bmp"],
    "image/webp": ["webp"],
    "image/svg+xml": ["svg"],
    "image/x-icon": ["ico"],
    "image/heic": ["heic"],
    "image/heif": ["heif"],
    "image/heic-sequence": ["hevc"],
    "image/tiff": ["tiff", "tif"],
    "image/x-raw": ["raw", "cr2", "nef", "orf", "sr2"],
    "image/vnd.adobe.photoshop": ["psd"],
    "application/postscript": ["ai", "eps"],
    "video/mp4": ["mp4"],
    "video/x-msvideo": ["avi"],
    "video/x-matroska": ["mkv"],
    "video/quicktime": ["mov"],
    "video/x-ms-wmv": ["wmv"],
    "video/x-flv": ["flv"],
    "video/webm": ["webm"],
    "video/x-m4v": ["m4v"],
    "video/3gpp": ["3gp"],
    "video/3gpp2": ["3g2"],
    "video/mj2": ["mj2"],
    "video/mp2t": ["m2ts", "mts", "m2t"],
    "video/mpeg": ["vob", "mpg", "mpeg"],
    "video/ogg": ["ogv"],
    "video/x-pn-realvideo": ["rm", "rmvb"],
    "video/x-ms-asf": ["asf"],
    "audio/mpeg": ["mp3"],
    "audio/wav": ["wav"],
    "audio/aac": ["aac"],
    "audio/flac": ["flac"],
    "audio/ogg": ["ogg"],
    "audio/x-ms-wma": ["wma"],
    "audio/x-m4a": ["m4a"],
    "audio/amr": ["amr"],
    "audio/aiff": ["aiff"],
    "audio/x-alac": ["alac"],
    "audio/opus": ["opus"],
    "audio/midi": ["mid", "midi"],
    "audio/x-pn-realaudio": ["ra"],
    "audio/basic": ["au"],
    "application/msword": ["doc"],
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ["docx"],
    "application/vnd.oasis.opendocument.text": ["odt"],
    "application/rtf": ["rtf"],
    "application/x-tex": ["tex"],
    "application/vnd.ms-excel": ["xls"],
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ["xlsx"],
    "application/vnd.oasis.opendocument.spreadsheet": ["ods"],
    "text/csv": ["csv"],
    "text/tab-separated-values": ["tsv"],
    "application/vnd.ms-powerpoint": ["ppt"],
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": ["pptx"],
    "application/vnd.oasis.opendocument.presentation": ["odp"],
    "application/vnd.apple.keynote": ["key"],
    "application/pdf": ["pdf"],
    "font/ttf": ["ttf"],
    "font/otf": ["otf"],
    "font/woff": ["woff"],
    "font/woff2": ["woff2"],
    "application/vnd.ms-fontobject": ["eot"],
    "application/x-font": ["fon"],
    "application/x-msdos-program": ["bat", "cmd"],
    "application/x-sh": ["sh"],
    "application/x-executable": ["bin", "run"],
    "application/vnd.android.package-archive": ["apk"],
    "application/x-ms-gadget": ["gadget"],
    "application/x-ms-windows-script": ["wsf"],
    "application/javascript": ["js", "jsx", "cjs", "mjs"],
    "application/typescript": ["ts", "tsx"],
    "text/x-python": ["py"],
    "text/x-java-source": ["java"],
    "text/x-c": ["c", "h"],
    "text/x-c++": ["cpp", "hpp"],
    "text/x-csharp": ["cs"],
    "text/x-ruby": ["rb"],
    "text/x-php": ["php", "php3", "php4", "php5", "php7", "phps", "phpt"],
    "text/x-go": ["go"],
    "text/x-rust": ["rs"],
    "text/x-swift": ["swift"],
    "text/x-kotlin": ["kt", "kts"],
    "text/x-scala": ["scala"],
    "text/x-perl": ["pl"],
    "text/x-shellscript": ["sh"],
    "text/x-msdos-batch": ["bat"],
    "text/x-powershell": ["ps1"],
    "text/x-lua": ["lua"],
    "text/x-r": ["r"],
    "text/x-objective-c": ["m"],
    "text/x-vb": ["vb"],
    "text/x-dart": ["dart"],
    "text/x-sql": ["sql"],
    "text/html": ["html", "htm"],
    "text/css": ["css"],
    "text/x-scss": ["scss"],
    "text/x-less": ["less"],
    "text/xml": ["xml"],
    "application/json": ["json"],
    "text/yaml": ["yml", "yaml"],
    "text/x-ini": ["ini"],
    "text/x-toml": ["toml"],
    "text/x-config": ["conf"],
    "text/x-asm": ["asm", "s"],
    "text/x-verilog": ["v"],
    "text/x-systemverilog": ["sv", "svh"],
    "text/x-vhdl": ["vhd", "vhdl"],
    "text/x-fsharp": ["fs", "fsx", "fsi", "fsscript"],
    "text/x-julia": ["jl"],
    "text/x-groovy": ["groovy"],
    "text/x-clojure": ["clj", "cljs", "cljc"],
    "text/x-edn": ["edn"],
    "text/x-coffeescript": ["coffee"],
    "application/x-ipynb+json": ["ipynb"],
    "text/plain": ["txt", "md", "rst", "log", "me", "readme", "changelog", "license"],
    "text/x-subrip": ["srt"],
    "text/x-microdvd": ["sub"],
    "text/x-ssa": ["ass", "ssa"],
    "text/vtt": ["vtt"],
    "text/x-subviewer": ["sbv"],
    "text/x-mplayer2": ["mpl"],
    "application/x-sqlite3": ["sqlite", "sqlite3", "db", "db3"],
    "application/x-msaccess": ["mdb", "accdb"],
    "application/x-mysql": ["frm", "myd", "myi"],
    "application/x-mssql": ["ndf", "ldf"],
    "application/x-sqlite": ["sdf"],
    "application/epub+zip": ["epub"],
    "application/x-mobipocket-ebook": ["mobi"],
    "application/vnd.amazon.ebook": ["azw", "azw3"],
    "application/x-fictionbook+xml": ["fb2"],
    "application/x-ms-reader": ["lit"],
    "application/x-palm-database": ["prc"],
    "application/x-ibooks+zip": ["ibooks"],
    "application/x-lzip": ["lz"],
    "application/x-lzma": ["lzma"],
    "application/x-gtar": ["tgz"],
    "application/x-bzip2-compressed-tar": ["tbz2"],
    "application/x-xz-compressed-tar": ["txz"],
    "application/x-efi": ["efi"],
};

export const getFileType = (ext: string): keyof typeof fileExtension | "file" => {
    for (const [key, value] of Object.entries(fileExtension)) {
        if (value.includes(ext)) return key as keyof typeof fileExtension;
    }
    return "file";
};

export const getFileIcon = (
    ext: string,
): {
    icon: IconType;
    color: (typeof accentColorPropDef)["color"]["values"][number];
} => {
    const fileType = getFileType(ext);
    return fileExtensionIcon[fileType];
};

export const getFileLanguage = (fileName: string): string => {
    const ext = fileName.split(".").pop()?.toLowerCase();
    if (!ext) return "plaintext";
    for (const [key, value] of Object.entries(editorFileLanguage)) {
        if (value.includes(ext)) return key;
    }
    return "plaintext";
};

export const getMimeType = (fileName: string): string => {
    const ext = fileName.split(".").pop()?.toLowerCase();
    if (!ext) return "application/octet-stream";
    for (const [key, value] of Object.entries(mimeType)) {
        if (value.includes(ext)) return key;
    }
    return "application/octet-stream";
};
